/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './pages/__root'
import { Route as ReportsLayoutRouteImport } from './pages/reports/layout'
import { Route as IndexRouteImport } from './pages/index'
import { Route as ReportsCreateRouteImport } from './pages/reports/create'
import { Route as ReportsCodeRouteImport } from './pages/reports/$code'
import { Route as AdminLoginRouteImport } from './pages/admin/login'
import { Route as AdminAuthLayoutRouteImport } from './pages/admin/_auth/layout'
import { Route as AdminAuthIndexRouteImport } from './pages/admin/_auth/index'
import { Route as AdminAuthReportsRouteImport } from './pages/admin/_auth/reports'

const AdminRouteImport = createFileRoute('/admin')()

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsLayoutRoute = ReportsLayoutRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsCreateRoute = ReportsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => ReportsLayoutRoute,
} as any)
const ReportsCodeRoute = ReportsCodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => ReportsLayoutRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuthLayoutRoute = AdminAuthLayoutRouteImport.update({
  id: '/_auth',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuthIndexRoute = AdminAuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAuthLayoutRoute,
} as any)
const AdminAuthReportsRoute = AdminAuthReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminAuthLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/reports': typeof ReportsLayoutRouteWithChildren
  '/admin': typeof AdminAuthLayoutRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/reports/$code': typeof ReportsCodeRoute
  '/reports/create': typeof ReportsCreateRoute
  '/admin/reports': typeof AdminAuthReportsRoute
  '/admin/': typeof AdminAuthIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reports': typeof ReportsLayoutRouteWithChildren
  '/admin': typeof AdminAuthIndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/reports/$code': typeof ReportsCodeRoute
  '/reports/create': typeof ReportsCreateRoute
  '/admin/reports': typeof AdminAuthReportsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/reports': typeof ReportsLayoutRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/admin/_auth': typeof AdminAuthLayoutRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/reports/$code': typeof ReportsCodeRoute
  '/reports/create': typeof ReportsCreateRoute
  '/admin/_auth/reports': typeof AdminAuthReportsRoute
  '/admin/_auth/': typeof AdminAuthIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/reports'
    | '/admin'
    | '/admin/login'
    | '/reports/$code'
    | '/reports/create'
    | '/admin/reports'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/reports'
    | '/admin'
    | '/admin/login'
    | '/reports/$code'
    | '/reports/create'
    | '/admin/reports'
  id:
    | '__root__'
    | '/'
    | '/reports'
    | '/admin'
    | '/admin/_auth'
    | '/admin/login'
    | '/reports/$code'
    | '/reports/create'
    | '/admin/_auth/reports'
    | '/admin/_auth/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReportsLayoutRoute: typeof ReportsLayoutRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/create': {
      id: '/reports/create'
      path: '/create'
      fullPath: '/reports/create'
      preLoaderRoute: typeof ReportsCreateRouteImport
      parentRoute: typeof ReportsLayoutRoute
    }
    '/reports/$code': {
      id: '/reports/$code'
      path: '/$code'
      fullPath: '/reports/$code'
      preLoaderRoute: typeof ReportsCodeRouteImport
      parentRoute: typeof ReportsLayoutRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/_auth': {
      id: '/admin/_auth'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAuthLayoutRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/_auth/': {
      id: '/admin/_auth/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAuthIndexRouteImport
      parentRoute: typeof AdminAuthLayoutRoute
    }
    '/admin/_auth/reports': {
      id: '/admin/_auth/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminAuthReportsRouteImport
      parentRoute: typeof AdminAuthLayoutRoute
    }
  }
}

interface ReportsLayoutRouteChildren {
  ReportsCodeRoute: typeof ReportsCodeRoute
  ReportsCreateRoute: typeof ReportsCreateRoute
}

const ReportsLayoutRouteChildren: ReportsLayoutRouteChildren = {
  ReportsCodeRoute: ReportsCodeRoute,
  ReportsCreateRoute: ReportsCreateRoute,
}

const ReportsLayoutRouteWithChildren = ReportsLayoutRoute._addFileChildren(
  ReportsLayoutRouteChildren,
)

interface AdminAuthLayoutRouteChildren {
  AdminAuthReportsRoute: typeof AdminAuthReportsRoute
  AdminAuthIndexRoute: typeof AdminAuthIndexRoute
}

const AdminAuthLayoutRouteChildren: AdminAuthLayoutRouteChildren = {
  AdminAuthReportsRoute: AdminAuthReportsRoute,
  AdminAuthIndexRoute: AdminAuthIndexRoute,
}

const AdminAuthLayoutRouteWithChildren = AdminAuthLayoutRoute._addFileChildren(
  AdminAuthLayoutRouteChildren,
)

interface AdminRouteChildren {
  AdminAuthLayoutRoute: typeof AdminAuthLayoutRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuthLayoutRoute: AdminAuthLayoutRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReportsLayoutRoute: ReportsLayoutRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
